// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
rtssc_path=get_absolute_file_path('loader.sce');
link(rtssc_path+'librtssc.dll',['rtss_scs_eul2tr_cf4','rtss_scs_tr2eul_cf4','rtss_scs_rpy2tr_cf4','rtss_scs_tr2rpy_cf4','rtss_scs_xyz2tr_cf4','rtss_scs_tr2xyz_cf4','rtss_scs_tr2diff_cf4','rtss_scs_fkine_cf4','rtss_scs_jacobn_cf4','rtss_scs_jacob0_cf4','rtss_scs_be_cf4','rtss_scs_fe_cf4','rtss_scs_singen_cf4','rtss_scs_square_cf4','rtss_scs_frne_cf4','rtss_scs_inertia_cf4','rtss_scs_coriolis_cf4','rtss_scs_gravload_cf4','rtss_scs_accel_cf4','rtss_scs_robot_cf4','rtss_scs_jtraj_cf4'],'c');
