// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
rtss_demo13_Dq0_path=get_absolute_file_path('loader.sce');
link(rtss_demo13_Dq0_path+'librtss_demo13_Dq0.dll',['rtss_demo13_Dq0'],'c');
