function [tree] = sci_is_real_matrix(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab is_real_matrix()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,-1)
tree.lhs(1).type=Type(Double,Real)
endfunction
