function [tree] = sci_narginchk(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab narginchk()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
endfunction
