function [tree] = sci_sys_prune(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab sys_prune()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,-1)
tree.lhs(1).type=Type(Unknown,Unknown)
endfunction
