function [tree] = sci_lti_dor_aptow(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab lti_dor_aptow()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(0,0)
tree.lhs(1).type=Type(Double,Real)
endfunction
