function [tree] = sci_lti_valve_a_1_ol(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab lti_valve_a_1_ol()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(0,0)
tree.lhs(1).type=Type(Double,Real)
endfunction
