function [tree] = sci_lti_man_1_mv(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab lti_man_1_mv()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,-1)
tree.lhs(1).type=Type(Unknown,Unknown)
endfunction
