function [tree] = sci_la_lrecptow(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab la_lrecptow()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,-1)
tree.lhs(1).type=Type(Double,Unknown)
endfunction
