function [tree] = sci_default(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab default()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
endfunction
