function [as, ad] = ven_reg_win(x, GEO)
xcrl    = max(min(-(x+GEO.DBIAS) - GEO.UNDERLAP, GEO.DORIFD), 0.);
xscl    = max(min((x+GEO.SBIAS), GEO.DORIFS), 0.);
thcrl   = acos(1. - xcrl * 2. / GEO.DORIFD);
thscl   = acos(1. - xscl * 2. / GEO.DORIFS);
alk     = GEO.CLEAR * (GEO.DORIFS + GEO.DORIFD)/2. * (pi - thcrl - thscl);
as     = GEO.HOLES * ( max(hole(max(min(x+GEO.SBIAS, GEO.DORIFS), 0.), GEO.DORIFS),...
			max(min(x+GEO.SBIAS, GEO.DORIFS),0.)*GEO.WS)...
			+ alk);
ad     = GEO.HOLES * ( max(holeArea(max(min(-(x+GEO.DBIAS) - GEO.UNDERLAP, GEO.DORIFD), 0.),...
		       GEO.DORIFD),...
			max(min(-(x+GEO.DBIAS) - GEO.UNDERLAP, GEO.DORIFD), 0.)*GEO.WD)...
		        + alk);
return


